version: '3'

services:

    datascience-notebook:
    # image: jupyter/datascience-notebook
      build: .
      container_name: jupyter-datascience
      environment:
        JUPYTER_TOKEN: "12345"
      volumes:
        - .:/home/jovyan
      ports:
        - '8888:8888'